-- Inventory Stock Management System
-- Fresh PostgreSQL setup script
--
-- Run this script against an empty PostgreSQL database, for example `inventory_db`.
-- It matches the current EF Core model in backend-api/Migrations/20260907121939_InitialCreate.cs
-- and seeds sample/master data without introducing a second database design.

BEGIN;

CREATE TABLE IF NOT EXISTS "Items" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ItemCode" character varying(50) NOT NULL,
    "ItemName" character varying(200) NOT NULL,
    "Category" character varying(100),
    "Unit" character varying(20) NOT NULL,
    "ReorderLevel" numeric(18,3) NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Items" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Stores" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Code" character varying(50) NOT NULL,
    "Name" character varying(200) NOT NULL,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_Stores" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "StockBalances" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "StoreId" integer NOT NULL,
    "ItemId" integer NOT NULL,
    "Quantity" numeric(18,3) NOT NULL,
    CONSTRAINT "PK_StockBalances" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_StockBalances_Items_ItemId" FOREIGN KEY ("ItemId") REFERENCES "Items" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_StockBalances_Stores_StoreId" FOREIGN KEY ("StoreId") REFERENCES "Stores" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "StockTransactions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TransactionNo" character varying(50) NOT NULL,
    "TransactionDate" timestamp with time zone NOT NULL,
    "TransactionType" integer NOT NULL,
    "StoreId" integer NOT NULL,
    "Remarks" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_StockTransactions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_StockTransactions_Stores_StoreId" FOREIGN KEY ("StoreId") REFERENCES "Stores" ("Id") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS "StockTransactionDetails" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "StockTransactionId" integer NOT NULL,
    "ItemId" integer NOT NULL,
    "Quantity" numeric(18,3) NOT NULL,
    "Unit" character varying(20) NOT NULL,
    "Remarks" character varying(500),
    CONSTRAINT "PK_StockTransactionDetails" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_StockTransactionDetails_Items_ItemId" FOREIGN KEY ("ItemId") REFERENCES "Items" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_StockTransactionDetails_StockTransactions_StockTransactionId" FOREIGN KEY ("StockTransactionId") REFERENCES "StockTransactions" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Items_ItemCode" ON "Items" ("ItemCode");
CREATE INDEX IF NOT EXISTS "IX_StockBalances_ItemId" ON "StockBalances" ("ItemId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_StockBalances_StoreId_ItemId" ON "StockBalances" ("StoreId", "ItemId");
CREATE INDEX IF NOT EXISTS "IX_StockTransactionDetails_ItemId" ON "StockTransactionDetails" ("ItemId");
CREATE INDEX IF NOT EXISTS "IX_StockTransactionDetails_StockTransactionId" ON "StockTransactionDetails" ("StockTransactionId");
CREATE INDEX IF NOT EXISTS "IX_StockTransactions_StoreId_TransactionDate" ON "StockTransactions" ("StoreId", "TransactionDate");
CREATE INDEX IF NOT EXISTS "IX_StockTransactions_TransactionDate" ON "StockTransactions" ("TransactionDate");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_StockTransactions_TransactionNo" ON "StockTransactions" ("TransactionNo");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Stores_Code" ON "Stores" ("Code");

-- TransactionType values used by the application:
-- 1 = Receipt
-- 2 = Issue
-- 3 = Transfer
-- 4 = Adjustment
-- 5 = OpeningBalance

INSERT INTO "Stores" ("Id", "Code", "Name", "IsActive") VALUES
    (1, 'STR-001', 'Main Warehouse', true),
    (2, 'STR-002', 'Branch Store', true);

INSERT INTO "Items" ("Id", "ItemCode", "ItemName", "Category", "Unit", "ReorderLevel", "IsActive", "CreatedAt", "UpdatedAt") VALUES
    (1, 'ITM-001', 'A4 Paper Ream', 'Stationery', 'REAM', 10.000, true, TIMESTAMPTZ '2026-09-01 00:00:00+00', TIMESTAMPTZ '2026-09-01 00:00:00+00'),
    (2, 'ITM-002', 'Ballpoint Pen Blue', 'Stationery', 'BOX', 5.000, true, TIMESTAMPTZ '2026-09-01 00:00:00+00', TIMESTAMPTZ '2026-09-01 00:00:00+00'),
    (3, 'ITM-003', 'USB Keyboard', 'IT Accessories', 'PCS', 8.000, true, TIMESTAMPTZ '2026-09-01 00:00:00+00', TIMESTAMPTZ '2026-09-01 00:00:00+00');

INSERT INTO "StockTransactions" ("Id", "TransactionNo", "TransactionDate", "TransactionType", "StoreId", "Remarks", "CreatedAt", "UpdatedAt") VALUES
    (1, 'OPEN-20260901-001', TIMESTAMPTZ '2026-09-01 00:00:00+00', 5, 1, 'Opening stock for main warehouse', TIMESTAMPTZ '2026-09-01 00:00:00+00', TIMESTAMPTZ '2026-09-01 00:00:00+00'),
    (2, 'REC-20260903-001', TIMESTAMPTZ '2026-09-03 00:00:00+00', 1, 1, 'Supplier receive', TIMESTAMPTZ '2026-09-03 00:00:00+00', TIMESTAMPTZ '2026-09-03 00:00:00+00'),
    (3, 'ISS-20260904-001', TIMESTAMPTZ '2026-09-04 00:00:00+00', 2, 1, 'Department issue', TIMESTAMPTZ '2026-09-04 00:00:00+00', TIMESTAMPTZ '2026-09-04 00:00:00+00'),
    (4, 'REC-20260905-001', TIMESTAMPTZ '2026-09-05 00:00:00+00', 1, 1, 'Additional receive', TIMESTAMPTZ '2026-09-05 00:00:00+00', TIMESTAMPTZ '2026-09-05 00:00:00+00'),
    (5, 'ISS-20260906-001', TIMESTAMPTZ '2026-09-06 00:00:00+00', 2, 1, 'Second issue', TIMESTAMPTZ '2026-09-06 00:00:00+00', TIMESTAMPTZ '2026-09-06 00:00:00+00'),
    (6, 'OPEN-20260901-002', TIMESTAMPTZ '2026-09-01 00:00:00+00', 5, 2, 'Opening stock for branch store', TIMESTAMPTZ '2026-09-01 00:00:00+00', TIMESTAMPTZ '2026-09-01 00:00:00+00'),
    (7, 'ISS-20260904-002', TIMESTAMPTZ '2026-09-04 00:00:00+00', 2, 2, 'Branch issue', TIMESTAMPTZ '2026-09-04 00:00:00+00', TIMESTAMPTZ '2026-09-04 00:00:00+00'),
    (8, 'REC-20260907-001', TIMESTAMPTZ '2026-09-07 00:00:00+00', 1, 2, 'Branch receive', TIMESTAMPTZ '2026-09-07 00:00:00+00', TIMESTAMPTZ '2026-09-07 00:00:00+00');

INSERT INTO "StockTransactionDetails" ("Id", "StockTransactionId", "ItemId", "Quantity", "Unit", "Remarks") VALUES
    (1, 1, 1, 50.000, 'REAM', 'Opening quantity'),
    (2, 1, 3, 30.000, 'PCS', 'Opening quantity'),
    (3, 2, 1, 50.000, 'REAM', 'Received from supplier'),
    (4, 3, 1, 10.000, 'REAM', 'Issued to department'),
    (5, 3, 3, 5.000, 'PCS', 'Issued to department'),
    (6, 4, 1, 20.000, 'REAM', 'Received from supplier'),
    (7, 5, 1, 15.000, 'REAM', 'Issued to department'),
    (8, 6, 2, 60.000, 'BOX', 'Opening quantity'),
    (9, 7, 2, 12.000, 'BOX', 'Issued to branch users'),
    (10, 8, 2, 51.000, 'BOX', 'Received from supplier');

-- StockBalances are seeded to match the transaction history above.
INSERT INTO "StockBalances" ("Id", "StoreId", "ItemId", "Quantity") VALUES
    (1, 1, 1, 95.000),
    (2, 1, 3, 25.000),
    (3, 2, 2, 99.000);

SELECT setval(pg_get_serial_sequence('"Stores"', 'Id'), COALESCE((SELECT MAX("Id") FROM "Stores"), 1), true);
SELECT setval(pg_get_serial_sequence('"Items"', 'Id'), COALESCE((SELECT MAX("Id") FROM "Items"), 1), true);
SELECT setval(pg_get_serial_sequence('"StockTransactions"', 'Id'), COALESCE((SELECT MAX("Id") FROM "StockTransactions"), 1), true);
SELECT setval(pg_get_serial_sequence('"StockTransactionDetails"', 'Id'), COALESCE((SELECT MAX("Id") FROM "StockTransactionDetails"), 1), true);
SELECT setval(pg_get_serial_sequence('"StockBalances"', 'Id'), COALESCE((SELECT MAX("Id") FROM "StockBalances"), 1), true);

COMMIT;
